### ISSUE TITLE
Keyboard Accessibility 

### ISSUE THREAD

**Issue by dsuriano** [pgrimard/react-toggle-switch#20]
### The Problem
Keyboard users are currently not able to interact with or toggle a `Switch`. 

### The Solution
Within `src/scripts/switch.js`, add a `tabIndex="0"` and `onKeyPress={e => (enabled ? onClick(e) : onDisabledClick(e))}` to the returned containing `div`.

### Bonus Points
Add a proper keypress handler that only listens for `enter` (keycode `13`) and `space` (keycode `32`).

**Comment by pgrimard** [comment]
Closing this issue because this repo is being archived and will no longer be maintained.
