### ISSUE TITLE
CWE-79 weakness in docs

### ISSUE THREAD

**Issue by maximdrozd** [pgrimard/react-toggle-switch#21]
In Bootstrap before 4.1.2, XSS is possible in the collapse data-parent attribute.

In Bootstrap before 4.1.2, XSS is possible in the data-target property of scrollspy.

In Bootstrap before 4.1.2, XSS is possible in the data-container property of tooltip.

In Bootstrap before 3.4.1 and 4.3.x before 4.3.1, XSS is possible in the tooltip or popover data-template attribute.

All inside react-toggle-switch/docs/scripts/bundle.min.js

**Comment by pgrimard** [comment]
Closing this issue because this repo is being archived and will no longer be maintained.
